### ISSUE TITLE
Configurable flagD metrics port

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#113]
In order to give flexibility we could add this e.g.

```
apiVersion: core.openfeature.dev/v1alpha1
kind: FeatureFlagConfiguration
metadata:
  name: featureflagconfiguration-sample
spec:
  flagDSpec:
    metricsPort: 8080
    envs:
    - name: FOO
      value: BAR
  featureFlagSpec: |
    {}
```
