### ISSUE TITLE
[Feature] Multiple FeatureFlagConfigurations per Deployment

### ISSUE THREAD

**Issue by thschue** [open-feature/open-feature-operator#17]
I think it should be possible to have multiple FeatureFlagConfigurations per Deployment/StatefulSet/Pod. Therefore, I'd propose that we make it possible to add multiple configurations to the `openfeature.dev/featureflagconfiguration` annotation. This might look like this:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    openfeature.dev: "enabled"
    openfeature.dev/featureflagconfiguration: "featureflagconfiguration-sample-1, featureflagconfiguration-sample-2"
```

When applied, this would create two ConfigMaps, which should get merged by flagd. We should think of which configuration should take precedence if a flag exists in both configurations and has the same weight set.
