### ISSUE TITLE
[Feature] Validation of incoming FeatureFlagConfiguration spec

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#2]
There is currently no validation done on the custom resource that is inserted into the cluster.
We need to create a validating admission webhook to check that the payload of the custom resource spec is valid Open Feature json.

**Comment by thschue** [comment]
I'd propose to do the implementation similarly to helm -> https://github.com/helm/helm/blob/main/pkg/chartutil/jsonschema.go. How should we deal with the schema definition itself in this case? Should this be stored in a configmap for the operator?

**Comment by AlexsJones** [comment]
I can take this, the idea here is to add a validating webhook we can build incrementally with more intense scrutinization, initially it can just check the spec is valid

**Comment by AlexsJones** [comment]
New admission structure I propose
```
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-pod
  failurePolicy: Ignore
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-v1-pod
  failurePolicy: Ignore
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: NoneOnDryRun

```
