### ISSUE TITLE
OFO configuration object + flagd upgrade path

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/open-feature-operator#270]
## usecase

As an operator
Given I want to upgrade flagd without upgrading OpenFeature operator
Then I should be able to increment configuration and objects to do so. 

As an operator
Given I want to enable open-feature-operator only on certain nodes
Then I should be able to allow for topology keys within a global object. 

### notes

_I think that adding an operator custom resource to enable upgrading would also allow us to utilize more dynamic global configuration secompprofile on/off, daemonset topology awareness) _

E.g.

```
apiVersion: core.openfeature.dev/v1alpha1
kind: OpenFeatureOperatorConfiguration
metadata:
  name: default
spec:
  flagvVrsion: v0.26
```

![Image](https://user-images.githubusercontent.com/1235925/205638533-7e6e6987-9dd2-4229-aa30-5f6879873253.png)
