### ISSUE TITLE
Unable to mount multiple FeatureFlagConfigurations ConfigMaps

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/open-feature-operator#319]
The following configuration causes flagd to fail on start up:

```yaml
---
apiVersion: core.openfeature.dev/v1alpha2
kind: FeatureFlagConfiguration
metadata:
  name: my-environment-ff
  namespace: open-feature-demo
spec:
  syncProvider:
    name: filepath
  featureFlagSpec:
    flags:
      enabledInDev:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "on"
---
apiVersion: core.openfeature.dev/v1alpha2
kind: FeatureFlagConfiguration
metadata:
  name: my-service-ff
  namespace: open-feature-demo
spec:
  syncProvider:
    name: filepath
  featureFlagSpec:
    flags:
      serviceSpecific:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
---
# Deployment of a demo-app using our custom resource
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-feature-demo-deployment
  namespace: open-feature-demo
  labels:
    app: open-feature-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-feature-demo
  template:
    metadata:
      labels:
        app: open-feature-demo
      annotations:
        openfeature.dev/enabled: "true"
        openfeature.dev/featureflagconfiguration: "my-service-ff,my-environment-ff"
```

The error looks like this:

```
Error creating: Pod "open-feature-demo-deployment-b4876c9fd-4vfgz" is invalid: spec.containers[1].volumeMounts[1].mountPath: Invalid value: "/etc/flagd/": must be unique
```

It looks like flagd is provided the file path and not individual files.
