### ISSUE TITLE
Move assignment of FF Configs from annotations to the FlagSourceConfiguration CR

### ISSUE THREAD

**Issue by heckelmann** [open-feature/open-feature-operator#355]
With the introduction of the additional flagd configuration Custom Resource (PR #344) opens up the possibility to entirely get rid of the `openfeature.dev/flagsourceconfiguration` annotation by extending the introduced CR with some additional fields. This would help with the separation of concerns.

```
apiVersion: core.openfeature.dev/v1alpha3
kind: FlagSourceConfiguration
metadata:
  name: end-to-end-test-fs-config
spec:
  selector:
    labelSelector:
      matchLabels:
        app: my-workload
  syncProviders:
  - source: end-to-end-test-filepath2
    provider: kubernetes
```

- As a platform operator this enables me to add for instance a cluster/environment-wide FF configuration too all deployments without changing the annotations for each deployment
- As a developer, I don't need to take care of the FF configuration deployment
