### ISSUE TITLE
Bug: naming a Service flagd breaks the networking of flagd deployment

### ISSUE THREAD

**Issue by skyerus** [open-feature/open-feature-operator#431]
Discovered while working on https://github.com/open-feature/open-feature-operator/pull/425

[This PR](https://github.com/open-feature/open-feature-operator/pull/430) demonstrates the issue.
Naming a Service `flagd` seems to break the networking of a deployment of flagd (as seen in the PR). Naming the Service anything but `flagd` functions as expected.

**Comment by skyerus** [comment]
Debugging eventually led to the discovery that [Kubernetes inserts a set of environment variables into pods](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables). Naming a service `flagd` means that an environment variable is inserted with name `FLAGD_PORT`, this conflicts with flagd's environment variables, leading to the wrong port being served.
Potential solutions:
- change the name of environment variables so that they don't conflict
- don't name a service flagd
- explicitly set the port in the args of the flagd container
e.g.
```yaml
containers:
        - image: ghcr.io/open-feature/flagd:v0.5.0
          imagePullPolicy: Never
          name: flagd
          ports:
            - containerPort: 8013
          args:
            - start
            - -f
            - file:/foo/flags.json
```
