### ISSUE TITLE
Allow custom resources definition

### ISSUE THREAD

**Issue by L3o-pold** [open-feature/open-feature-operator#511]
We need to be able to specify custom resource definition for the sidecar.

Something like this I guess.

```yaml
apiVersion: core.openfeature.dev/v1alpha3
kind: FlagSourceConfiguration
metadata:
    name: flag-source-sample
spec:
    metricsPort: 8080
    Port: 80
    evaluator: json
    image: my-custom-sidecar-image
    defaultSyncProvider: filepath
    resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
```
