### ISSUE TITLE
Allow OTEL collector

### ISSUE THREAD

**Issue by L3o-pold** [open-feature/open-feature-operator#512]
We need to be able to setup the OTEL collector uri

Something like this I guess.

```yaml
apiVersion: core.openfeature.dev/v1alpha3
kind: FlagSourceConfiguration
metadata:
    name: flag-source-sample
spec:
    metricsPort: 8080
    Port: 80
    evaluator: json
    image: my-custom-sidecar-image
    defaultSyncProvider: filepath
    otelCollectorUri: localhost:4317
```
