### ISSUE TITLE
how to leverage OFO for workloads external to k8s , say a web frontend or something running outside k8s

### ISSUE THREAD

**Issue by rjdp** [open-feature/open-feature-operator#615]
I am using OFO, and it works great for backend deployments that are in my cluster, how can i use it for my frontend applications or application outside of k8s

**Comment by toddbaert** [comment]
Hey @rjdp . Great observation. It's entirely possible to stand up a single flagd that watches a number of CRDs and isn't injected into a workload pod, and then expose that via an ingress to the outside world so that you could call it with the flagd-web provider, or perhaps [OFREP](https://github.com/open-feature/protocol) providers which are under active development.

This pattern _could_ be supported by OFO APIs itself, but we currently don't have any such plans. Once question would be how far to go... would OFO just setup the centralized flagd? Or would is also expose it (maybe with the gateway API)? I think exposing it would be a tall order, but I'm not sure...

Interested in other takes on this, especially from some people who have tinkered in this area already, cc @Kavindu-Dodan @bacherfl @thisthat 

@thomaspoignant @lukas-reining might be slightly interesting considering OFREP developments.

**Comment by lukas-reining** [comment]
I also like the suggestion, I lately thought about this too after adding updating flagd to the new version OFREP in the playground and used it for my local version of the cloud-native demo. 
So I am totally for adding an option for this.

Regarding the `Ingress` or maybe even `Gateway`:
Looking at e.g. the Jaeger operator I think it makes sense and is doable to even include optional ingress generation.
By the Jaeger operator, services are created always and an ingress can be created optionally too.

The following is how it works with the Jaeger operator and I think it makes sense to do this for OFREP too.

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  namespace: open-feature-demo
  name: jaeger
spec:
  strategy: allinone
  allInOne:
      query:
        base-path: "/"
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: prod-issuer
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      kubernetes.io/ingress.class: nginx
    hosts:
      - jaeger.of-cloud-native.reining.dev
    tls:
      - hosts:
          - jaeger.of-cloud-native.reining.dev
        secretName: of-demo-jaeger-server-tls´
```

An inspiration could be the CRD of Jaeger: https://github.com/jaegertracing/jaeger-operator/blob/main/docs/api.md#jaegerspecingress

Currently I think `Ingress` is still more common, so also more important, but we could also directly add the options for the `Gateway` API.
