### ISSUE TITLE
[Feature] Customise flagD port via custom resource

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#63]
Often the flagD port will conflict with metrics or operator endpoints.
It is optimal to be able to inject a dynamic port when it is set in the CR..

e.g. 

```
apiVersion: core.openfeature.dev/v1alpha1
kind: FeatureFlagConfiguration
metadata:
  name: watchman-flags
  namespace: watchman-system
spec:
  flagD:
    port: 8085
  featureFlagSpec: |
    {
      "flags": {
        "blocking": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "on"
        }
      }
    }

```

**Comment by AlexsJones** [comment]
https://github.com/open-feature/open-feature-operator/pull/64

**Comment by beeme1mr** [comment]
I'm wondering if this would be a good opportunity to have the operator set environment variables. In this case, the pod may set something like `FLAGD_PORT`. The SDKs and flagD would be able to use this environment variable to use the correct port without any additional configuration.

If you think the approach, we should think about formally defining an environment variable prefix (i.e. FLAGD) and create issues for other configurations options (i.e. gRPC, HTTP).

**Comment by AlexsJones** [comment]
We could also add those kinds of capabilities absolutely, I don't have a use case right now. 
Also in the example of the `port` we can set that as an environmental inside of flagD if that helps to populate the providers.. I suppose we need to think about integrating a provider to know what are the gaps.

**Comment by skyerus** [comment]
**Desired outcome**
Inject environment variables into flagd & application containers from a single source ([flagd now supports environment variables](https://github.com/open-feature/flagd/pull/142)).

**Suggested solution**
Create a config map with environment variables as data:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  FLAGD_PORT: "8013"
  FLAGD_SERVICE_PROVIDER: "http"
  FLAGD_SYNC_PROVIDER: "filepath"
  FLAGD_EVALUATOR: "json"
  FLAGD_URI: "/etc/flagd/config.json"
```
Reference this config map in the app deployment's container
```
    spec:
      containers:
        - name: open-feature-demo
          image: ghcr.io/open-feature/open-feature-demo:latest
          envFrom:
            - configMapRef:
                name: environment
```
Inject the same `envFrom` into the flagd sidecar.

Any concerns with this approach? @beeme1mr @toddbaert @AlexsJones @thschue @james-milligan 

If not I'll proceed with it.

**Comment by toddbaert** [comment]
@skyerus I was thinking the mutating admission webhook would parse the flagd settings spec (as it already exists) and then set these vars on both the workload container and the flagd container. Is that what you mean? Users would never mention `FLAGD_PORT` themselves explicitly in any configmap.

**Comment by skyerus** [comment]
@toddbaert where does the flagd settings spec already exist?
Is the workload container the application (consumer of the sdk) container?
The user would only have to reference the already existing config map in their container spec (as shown in the example above).
I’m not sure if we’re thinking of the same approach here.

**Comment by beeme1mr** [comment]
I think the flow may look something like this:

1. Create a CRD for the feature flag. It may look something like this:

```yaml
apiVersion: core.openfeature.dev/v1alpha1
kind: FeatureFlagConfiguration
metadata:
  name: watchman-flags
  namespace: watchman-system
spec:
  flagD:
    port: 8085
  featureFlagSpec: |
    {
      "flags": {
        "blocking": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "on"
        }
      }
    }
```

2. The controller would create a ConfigMap using the flagD configurations.

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: watchman-flags-settings
data:
  FLAGD_PORT: 8085
```

3. The mutating webhook would automatically set the `watchman-flags-settings` ConfigMap on flagD and the pod with the flagD annotations.
