### ISSUE TITLE
sidecarConfiguration.resources in helm chart is ignored

### ISSUE THREAD

**Issue by mng1dev** [open-feature/open-feature-operator#630]
Hello, 

I am trying to use the operator and I am installing it via helm chart.

I am passing the following `values.yaml` file, but it doesn't seem to affect the default properties of the `flagd` sidecar.

Am I doing anything wrong?

```yaml
sidecarConfiguration:
  resources:
    requests:
      cpu: 10m
      memory: 16M
    limits:
      cpu: 50m
      memory: 32M
```
