### ISSUE TITLE
[BUG] InProcessConfiguration not injecting env-vars if set to default

### ISSUE THREAD

**Issue by toddbaert** [open-feature/open-feature-operator#646]
If I set an InProcessConfiguration like this:

```yaml
apiVersion: core.openfeature.dev/v1beta1
kind: InProcessConfiguration
metadata:
    name: in-process-config
spec:
    host: flagd-standalone
    port: 8015
```
the resulting container looks like this (note `FLAGD_PORT` is missing):

![image](https://github.com/open-feature/open-feature-operator/assets/25272906/66b3ba67-19d2-49e0-9a68-30297d3dfc72)

If I change the port to something other than `8015` like this:

```yaml
apiVersion: core.openfeature.dev/v1beta1
kind: InProcessConfiguration
metadata:
    name: in-process-config
spec:
    host: flagd-standalone
    port: 8033
```

Then the var is set (note `FLAGD_PORT` is now set to `8033` as expected): 

![image](https://github.com/open-feature/open-feature-operator/assets/25272906/a1aff19e-0346-423c-81ea-98489b31a945)
