### ISSUE TITLE
[Feature] FeatureFlagConfiguration should track the related consumers of the CR

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#7]
In order to keep a listing of who is consuming the feature flag CR then we should implement a track in the status field 
e.g. 
```
status: 
  consumers:
  - name:
    namespace:
    type:
```
