### ISSUE TITLE
Improve flagD CRD Structure

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/open-feature-operator#72]
## Overview

The current flagD CRD expects `featureFlagSpec` as a string. Various tools (i.e. Lens) use the OpenAPI V3 Schema exposed by Kubernetes to provide basic configuration UIs and input validation. It may be possible to update the current CRD to include the flagD flag configuration json schema.

## Resources

- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
- https://www.pulumi.com/blog/introducing-crd2pulumi/

https://github.com/open-feature/open-feature-operator/issues/72#tasklist-block-cde58e47-d88d-41f4-b5ca-5a43c6f5f0c0

**Comment by AlexsJones** [comment]
```
apiVersion: core.openfeature.dev/v1alpha1
kind: FeatureFlagConfiguration
metadata:
  name: featureflagconfiguration-sample
spec:
  flagDSpec:
    envs:
    - name: FOO
      value: BAR
  featureFlagSpec: 
    flags:
      myBoolFlag:
        state: ENABLED
        variants:
          'on': true
          'off': false
        defaultVariant: 'on'
      myStringFlag:
        state: ENABLED
        variants:
          key1: val1
          key2: val2
        defaultVariant: key1
      myFloatFlag:
        state: ENABLED
        variants:
          one: 1.23
          two: 2.34
        defaultVariant: one
      myIntFlag:
        state: ENABLED
        variants:
          one: 1
          two: 2
        defaultVariant: one
      myObjectFlag:
        state: ENABLED
        variants:
          object1:
            key: val
          object2:
            key: true
        defaultVariant: object1
      isColorYellow:
        state: ENABLED
        variants:
          'on': true
          'off': false
        defaultVariant: 'off'
        targeting:
          if:
          - "==":
            - var:
              - color
            - yellow
          - 'on'
          - 'off'
      fibAlgo:
        variants:
          recursive: recursive
          memo: memo
          loop: loop
          binet: binet
        defaultVariant: recursive
        state: ENABLED
        targeting:
          if:
          - "$ref": emailWithFaas
          - binet
          -
      headerColor:
        variants:
          red: "#FF0000"
          blue: "#0000FF"
          green: "#00FF00"
          yellow: "#FFFF00"
        defaultVariant: red
        state: ENABLED
        targeting:
          if:
          - "$ref": emailWithFaas
          - fractionalEvaluation:
            - email
            - - red
              - 25
            - - blue
              - 25
            - - green
              - 25
            - - yellow
              - 25
          -
    "$evaluators":
      emailWithFaas:
        in:
        - "@faas.com"
        - var:
          - email
```

Thinking of something more like this?
